config/routes.rb
Rails.application.routes.draw do

  get 'game_of_life/conway'

  root      'static_pages#home'
  get       'about'             => 'static_pages#about'
  get       'help'              => 'static_pages#help'
  get       'contact'           => 'static_pages#contact'

  get       'signup'            => 'users#new'

  get       'login'             => 'sessions#new'
  post      'login'             => 'sessions#create'
  delete    'logout'            => 'sessions#destroy'

  get       'feed'              => 'microposts#feed'

  get       'conway_s_game_of_life' => 'game_of_life#conway'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    My <a href="http://binchan.me/">Toy App</a>
    created according to
    <a href="http://www.railstutorial.org/">Michael Hartl's rails tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Rss", feed_path + ".rss" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "MY TOY APP", root_path, id: "logo" %>
    <nav>
      <ul>
        <li><%= link_to "Home",   root_path %></li>
        <% if not logged_in? %>
          <li><%= link_to "My Posts", root_path + 'users/1' %></li>
        <% end %>
        <li><%= link_to t('Help'),   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to t("Settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= auto_discovery_link_tag(:rss, "http://localhost:3000/feed.rss") %>
  <head>
    <title><%= yield(:title) %> - My Toy App</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>